"""empty message

Revision ID: 8e590aa03181
Revises: b358d8b838da
Create Date: 2019-01-29 21:52:02.201567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e590aa03181'
down_revision = 'b358d8b838da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('requestQuantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'requestQuantity')
    # ### end Alembic commands ###
